# The `meta` group contains top level attributes that govern the
# behaviour of the MPM Solver.
#
# Attributes:
# title:    The title of the experiment. This is just for the user's
#           reference.
# type:     The type of simulation to be used. Allowed values are
#           {"MPMExplicit"}
# scheme:   The MPM Scheme used for simulation. Allowed values are
#           {"usl", "usf"}
# dt:       Timestep used in the simulation.
# nsteps:   Number of steps to run the simulation for.
[meta]
title = "plate-with-a-hole"
type = "MPMExplicit"
dimension = 2
scheme = "usf"
dt = 0.0001
nsteps = 300000
velocity_update = true

[output]
format = "npz"
folder = "results/"
step_frequency = 1000

[mesh]
# type = "file"
# file = "mesh-1d.txt"
# boundary_nodes = "boundary-1d.txt"
# particle_element_ids = "particles-elements.txt"
type = "generator"
nelements = [64, 40]
element_length = [0.0625, 0.0625]
particle_element_ids = [0]
element = "Quadrilateral4Node"
entity_sets = "entity_sets.json"
    
[[mesh.constraints]]
nset_ids = [0]
dir = 0
velocity = 0.00

[[mesh.constraints]]
nset_ids = [1]
dir = 1
velocity = 0.00

[[materials]]
id = 0
density = 2000.0
poisson_ratio = 0.0
youngs_modulus = 1000000
type = "LinearElastic"

[[particles]]
file = "particles-2d-plate-with-hole.json"
material_id = 0
init_velocity = 0.0

[external_loading]
gravity = [0, 0]

[[external_loading.particle_surface_traction]]
pset = [0]
pset_ids = [0]
math_function_id = 0
dir = 0
traction = 1

[[math_functions]]
type = "Linear"
xvalues = [0.0, 0.5, 1.0]
fxvalues = [0.0, 1.0, 1.0]